### ISSUE TITLE
scatter with -g not showing probes or segmentation

### ISSUE THREAD

**Issue by ferenju1** [etal/cnvkit#461] opened 2019-07-03 00:23 UTC
Hi,

I've just upgraded from the python2.7 version of cnvkit to python3, but I'm having a problem producing scatter plots with the -g option. Genome level and chromosome level plots are fine. I'm using cns/cnr files produced with the python 2.7 version of cnvkit.

Here's the output from **cnvkit.py scatter -s xxx.cn{s,r} -g CDKN2A -c 9**, which is correct

![Chr9](https://user-images.githubusercontent.com/22363969/60554391-c351ce00-9d7a-11e9-9d0e-ef3ca2939b6e.png)

and the output from **cnvkit.py scatter -s xxx.cn{s,r} -g CDKN2A**, which is not correct

![CDKN](https://user-images.githubusercontent.com/22363969/60554667-c8634d00-9d7b-11e9-9522-4aa5dbb1ccb1.png)

If I try to specify any range by co-ordinates I get the same problem, e.g. cnvkit.py scatter -s xxx.cn{s,r} -c 9:20968195-22994383 gives a plot with no data points - this should show the point and segmentation around the gene CDKN2A.

I've installed a new python 3.7 env using conda and have these library versions installed:
asn1crypto==0.24.0
biopython==1.73
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
CNVkit==0.9.6
conda==4.7.5
conda-package-handling==1.3.10
cryptography==2.7
cycler==0.10.0
decorator==4.4.0
et-xmlfile==1.0.1
future==0.17.1
idna==2.8
jdcal==1.4.1
joblib==0.13.2
kiwisolver==1.1.0
libarchive-c==2.8
lxml==4.3.4
matplotlib==3.1.1
mkl-fft==1.0.13
mkl-random==1.0.4
networkx==1.11
numpy==1.16.4
olefile==0.46
openpyxl==2.6.2
pandas==0.24.2
Pillow==6.0.0
pomegranate==0.10.0
pybedtools==0.8.0
pycosat==0.6.3
pycparser==2.19
pyfaidx==0.5.5.2
pyOpenSSL==19.0.0
pyparsing==2.4.0
pysam==0.15.2
PySocks==1.7.0
python-dateutil==2.8.0
python-docx==0.8.10
pytz==2019.1
PyYAML==5.1.1
reportlab==3.5.23
requests==2.22.0
ruamel-yaml==0.15.71
scipy==1.3.0
six==1.12.0
tornado==6.0.3
tqdm==4.32.2
urllib3==1.24.3
xlrd==1.2.0

I'm not sure where to start debugging this...!

**Comment by ferenju1** [comment] 2019-07-03 07:29
I've tried re-installing a new python env, but the issue still remains...

**Comment by ferenju1** [comment] 2019-07-05 06:00
So, it appears that this problem is happening on v0.9.6  with python2.7 as well as 3.7 (at least on my mac).

I downgraded to v0.9.5 and it works - I've had to revert to python3.6.3 in order to maintain compatibility with other packages that I need to run as well, but at least the cnv plots are working as they should.

**Comment by ferenju1** [comment] 2019-07-10 03:27
Although v0.9.5 correctly draws plots for specific genes, I discovered a pre-reported bug in v0.9.5 that prevents chromosomal plots - https://www.biostars.org/p/326154/. 
So, I've reverted to v0.9.3 - this is the last version that can plot both chromosome regions and specific genes correctly. This appears to be working correctly.

**Comment by ViktorHy** [comment] 2019-07-10 14:01
I have the same problem, described in issue #457

**Comment by etal** [comment] 2019-11-11 23:36
Thanks for reporting. Sorry for the trouble and the long delay. Looks like a recent regression, but should be easy to fix.

**Comment by RoseString** [comment] 2020-04-09 22:16
Hello, is this issue currently fixed? I ran into the same problem with 0.9.6. Thx!

**Comment by etal** [comment] 2020-04-13 17:29
@RoseString Could you try the 0.9.7-beta release and see if it's still present there?

**Comment by t100114** [comment] 2020-08-13 09:32
Hi, I'm also having the same problem on the 0.9.7. I would be happy if you could let us know the solution. Thank you.

**Comment by etal** [comment] 2020-08-31 22:46
This might be fixed as of PR #536 (as was issue #535 ). Could you pull the latest from the master branch and see if it works for you now?

**Comment by tskir** [comment] 2020-09-15 18:47
I have verified that the most recent PR #541 fixes all scatter modes. @ferenju1 @ViktorHy @RoseString @t100114 you can use this branch to see if it indeed solves the issues for you: https://github.com/tskir/cnvkit/tree/fix-scatter-whole-chromosome

**Comment by etal** [comment] 2020-09-15 19:43
Great, I've merged that PR so it should be available on the master branch now.

**Closed** 2020-09-15 19:42 UTC
Labels: bug, plots
