### ISSUE TITLE
CNVkit batch issue

### ISSUE THREAD

**Issue by NIBIL401** [etal/cnvkit#876] opened 2024-03-26 12:34 UTC
The cnvkit batch command is not working for version  0.9.11.dev0. It is not running and doesnot showing any error

**Comment by bagieutopia** [comment] 2024-04-08 05:05
cnvkit.py batch S17_repeat.sorted.bam -n hg38_flatreference.cnn --targets hg38_exome_twist.bed --antitargets hg38_antitargets.bed --fasta ../reference/hg38.fa -d cnv/
i used this command to run cnvkit in batch mode for 1 whole exome sequencing cancer sample. The targets bed file was taken from the twist biosciences website. this is the error I'm getting: ValueError: file does not contain alignment data
I've checked my sorted bam file and my hg38 bed file cant find anything wrong, also updated the cnvkit version nothing worked I don't know what the issue is..please help!!

**Comment by etal** [comment] 2024-04-09 19:21
@NIBIL401  Multiprocessing tends to gobble up the error messages and any traceback. Can you try it with `-p 1`?

@bagieutopia My guess is that various updates and deprecations in `pandas` and the type system have broken some functionality. I'm resolving these in PR #878 . Would you like to try the development branch `fixes0424` and see if the batch command works for you there?

**Closed** 2024-04-12 21:28 UTC
Labels: bug
